version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - gocyclo
    - errcheck
    - ineffassign
    - unused
    - gocritic
    - gosec
    - prealloc

  settings:
    gocyclo:
      # Report functions with cyclomatic complexity > 15, so 15 is the
      # maximum allowed complexity.
      min-complexity: 9

formatters:
  default: none
  enable:
    - gofmt
