version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - gocyclo
    - errcheck
    - ineffassign
    - unused
    - gocritic
    - gosec
    - prealloc
    - revive
    # - gocritic

  settings:
    # gocritic:
    #   enable-all: true
    gocyclo:
      # min-complexity is the maximum allowed complexity.
      min-complexity: 3
    revive:
      rules:
        # Sets the maximum allowed lines per file
        - name: file-length-limit
          arguments:
            max: 350

formatters:
  default: none
  enable:
    - gofmt
